name: End to End Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install create-nextjs-storybook
        run: pnpm install
        working-directory: packages/create-nextjs-storybook
      - name: Build create-nextjs-storybook
        run: pnpm build
        working-directory: packages/create-nextjs-storybook
      - name: Install scripts
        run: pnpm install && pnpm exec playwright install
        working-directory: scripts
      # - uses: lhotari/action-upterm@v1
      - name: Run E2E Tests
        uses: BerniWittmann/background-server-action@v1
        with:
          cwd: scripts
          start: pnpm ts-node test.ts
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
          command: pnpm playwright test
